---
version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: daily
    target-branch: v3.7
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: daily
    target-branch: v3.8
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /.devcontainer/
    schedule:
      interval: daily
    target-branch: v3.9
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v3.7
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v3.8
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: v3.9
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    target-branch: master
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    target-branch: v3.7
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    target-branch: v3.8
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    target-branch: v3.9
    open-pull-requests-limit: 10
